service: functions
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  addingUser:
    handler: src/handlers/users/addUsersThroughChannel/usersInChannels/addUserThroughChannel.handler
    events:
      - httpApi:
          path: slack/addUser
          method: post

  addingUserChannel:
    handler: src/handlers/users/addUsersThroughChannel/addNewUserThroughChannel/memberAddedThroughChannel.handler
    events:
      - httpApi:
          path: slack/addUserChannel
          method: post

  removingUserChannel:
    handler: src/handlers/users/removedUserChannel/removedUserChannel.handler
    events:
      - httpApi:
          path: slack/removeUserChannel
          method: post

  add_allUsers:
    handler: src/handlers/users/addingAllUsers/addingAllUsers.handler
    events:
      - httpApi:
          path: slack/adding_allUsers
          method: post

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
